version: "3.7"

services:
  ruby_dev:
    build: .
    container_name: ruby_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
volumes:
  db:
